[vars]
SUPABASE_URL = "https://dvieojudteyiaoadeybo.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aWVvanVkdGV5aWFvYWRleWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NzI5NTEsImV4cCI6MjA4MzQ0ODk1MX0.s8Vup_TMz1X9Y_g-wyq8T9dzymt81BsjXRT2T41WUAk"

EMAILJS_PUBLIC_KEY = "1FgA7BuIawuOIZX40"
EMAILJS_SERVICE_ID = "service_ijz955b"
EMAILJS_TEMPLATE_ADMIN = "template_vhrd33g"
EMAILJS_TEMPLATE_CUSTOMER = "template_l8b7462"